crds:
  enabled: true

replicaCount: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "1.0.0.1"

prometheus:
  servicemonitor:
    # TODO: enable this once i add prometheus
    enabled: false

dns01RecursiveNameservers: "1.1.1.1:53,1.0.0.1:53"
dns01RecursiveNameserversOnly: true
