serviceType: LoadBalancer

prometheus:
  service:
    enabled: true
  monitor:
    # TODO: enable this when i add prometheus
    enabled: false

service:
  loadBalancerIP: 192.168.1.100

isClusterService: false

servers:
  - zones:
      - zone: .
        use_tcp: true
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 10s
      - name: ready
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: home.mattprovost.dev 192.168.1.101
      - name: forward
        parameters: . 1.1.1.1 1.0.0.1
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
