deployment:
  kind: DaemonSet

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingressClass:
  enabled: true
  isDefaultClass: true
  name: "tendril-traefik"

# TODO: don't expose this publicly in prod
ingressRoute:
  dashboard:
    enabled: true
  healthcheck:
    enabled: true
