deployment:
  kind: DaemonSet

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.home.mattprovost.dev`)
    entryPoints: ["websecure", "traefik"]
    middlewares:
      - name: authentik-authentik@kubernetescrd
  healthcheck:
    enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true

# register the dns record in coredns
service:
  ipFamilyPolicy: RequireDualStack
  annotations:
    "coredns.io/hostname": "traefik.home.mattprovost.dev"
