apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: wildcard-tls
  commonName: "{{ .Values.hostname }}"
  dnsNames:
    - "{{ .Values.hostname }}"
    - "*.{{ .Values.hostname }}"
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
