image:
  repository: glanceapp/glance
  tag: v0.8.4
  pullPolicy: IfNotPresent

containerPort: 8080
servicePort: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls: []
