repositories:
  - name: kubitodev
    url: https://charts.kubito.dev
  - name: traefik
    url: https://traefik.github.io/charts
  - name: coredns
    url: https://coredns.github.io/helm
  - name: k8s_gateway
    url: https://k8s-gateway.github.io/k8s_gateway/

releases:
  - name: cloudflared-secrets
    namespace: cloudflared
    chart: ./charts/cloudflared-secrets/
    values:
      - values.secrets.yaml
      - values.yaml

  - name: cloudflared
    namespace: cloudflared
    chart: kubitodev/cloudflared
    version: 1.7.0
    values:
      - values/cloudflared.values.yaml

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 36.3.0
    values:
      - values/traefik.values.yaml

  - name: k8s-gateway
    namespace: k8s-gateway
    chart: k8s_gateway/k8s-gateway
    version: 3.2.1
    values:
      - values/k8s_gateway.values.yaml

  - name: coredns
    namespace: kube-system
    chart: coredns/coredns
    version: 1.43.0
    needs:
      - k8s-gateway/k8s-gateway
    values:
      - values/coredns.values.yaml

  - name: glance
    namespace: glance
    chart: ./charts/glance/
    needs:
      - cloudflared/cloudflared
      - traefik/traefik
      - kube-system/coredns
    values:
      - values.yaml
