repositories:
  - name: kubitodev
    url: https://charts.kubito.dev
  - name: traefik
    url: https://traefik.github.io/charts
  - name: coredns
    url: https://coredns.github.io/helm
  - name: k8s_gateway
    url: https://k8s-gateway.github.io/k8s_gateway/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: authentik
    url: https://charts.goauthentik.io
  - name: pajikos
    url: https://pajikos.github.io/home-assistant-helm-chart/
  - name: t3n
    url: https://storage.googleapis.com/t3n-helm-charts
  - name: zigbee2mqtt
    url: https://charts.zigbee2mqtt.io

releases:
  - name: postgres
    namespace: postgres
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.7.20
    values:
      - values/postgres.values.yaml

  - name: redis
    namespace: redis
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 21.2.12
    values:
      - values/redis.values.yaml

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 36.3.0
    disableValidation: true
    values:
      - values/traefik.values.yaml

  - name: k8s-gateway
    namespace: k8s-gateway
    chart: k8s_gateway/k8s-gateway
    version: 3.2.1
    values:
      - values/k8s_gateway.values.yaml

  - name: coredns
    namespace: coredns
    chart: coredns/coredns
    version: 1.43.0
    needs:
      - k8s-gateway/k8s-gateway
    values:
      - values/coredns.values.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.18.2
    values:
      - values/cert-manager.values.yaml

  - name: cert-issuer
    namespace: cert-manager
    chart: ./charts/cert-issuer/
    disableValidation: true
    needs:
      - cert-manager/cert-manager
      - traefik/traefik
    values:
      - values.yaml

  - name: authentik
    namespace: authentik
    chart: authentik/authentik
    version: 2025.6.3
    disableValidation: true
    needs:
      - postgres/postgres
      - redis/redis
    values:
      - values/authentik.values.yaml

  - name: cloudflared
    namespace: cloudflared
    chart: kubitodev/cloudflared
    version: 1.7.0
    needs:
      - coredns/coredns
    values:
      - values/cloudflared.values.yaml

  - name: glance
    namespace: glance
    chart: ./charts/glance/
    needs:
      - cloudflared/cloudflared
      - traefik/traefik
      - coredns/coredns
    values:
      - values.yaml

  - name: mosquitto
    namespace: mosquitto
    chart: t3n/mosquitto
    version: 2.4.0
    values:
      - values/mosquitto.values.yaml

  - name: zigbee2mqtt
    namespace: zigbee2mqtt
    chart: zigbee2mqtt/zigbee2mqtt
    version: 2.5.1
    needs:
      - mosquitto/mosquitto
    values:
      - values/zigbee2mqtt.values.yaml

  - name: home-assistant
    namespace: home-assistant
    chart: pajikos/home-assistant
    version: 0.3.12
    needs:
      - traefik/traefik
    values:
      - values/home-assistant.values.yaml
