apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glance.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "glance.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "glance.name" . }}
    spec:
      containers:
        - name: glance
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: glance-config
