apiVersion: v1
kind: Service
metadata:
  name: {{ include "glance.fullname" . }}
spec:
  selector:
    app: {{ include "glance.name" . }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
